import os

files = {
    "src/config/database.js": "const { Pool } = require('pg');\nrequire('dotenv').config();\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\nmodule.exports = pool;",
    "src/config/cloudinary.js": "const cloudinary = require('cloudinary').v2;\nrequire('dotenv').config();\ncloudinary.config({ cloud_name: process.env.CLOUDINARY_CLOUD_NAME, api_key: process.env.CLOUDINARY_API_KEY, api_secret: process.env.CLOUDINARY_API_SECRET });\nmodule.exports = cloudinary;",
    "src/middleware/auth.js": "const jwt = require('jsonwebtoken');\nmodule.exports = (req, res, next) => {\n  const token = req.headers.authorization?.split(' ')[1];\n  if (!token) return res.status(401).json({ erro: 'Token nao fornecido' });\n  try { req.usuario = jwt.verify(token, process.env.JWT_SECRET); next(); }\n  catch { res.status(401).json({ erro: 'Token invalido' }); }\n};",
    "src/controllers/authController.js": "const pool = require('../config/database');\nconst bcrypt = require('bcryptjs');\nconst jwt = require('jsonwebtoken');\nexports.login = async (req, res) => {\n  try {\n    const { email, senha } = req.body;\n    const result = await pool.query('SELECT * FROM funcionarios WHERE email = $1', [email]);\n    const user = result.rows[0];\n    if (!user || !await bcrypt.compare(senha, user.senha_hash))\n      return res.status(401).json({ erro: 'Credenciais invalidas' });\n    const token = jwt.sign({ id: user.id, nome: user.nome, perfil: user.perfil }, process.env.JWT_SECRET, { expiresIn: '12h' });\n    res.json({ token, usuario: { id: user.id, nome: user.nome, email: user.email, perfil: user.perfil } });\n  } catch (e) { res.status(500).json({ erro: e.message }); }\n};\nexports.cadastrar = async (req, res) => {\n  try {\n    const { nome, email, senha, cargo, departamento } = req.body;\n    const hash = await bcrypt.hash(senha, 10);\n    const result = await pool.query('INSERT INTO funcionarios (nome, email, senha_hash, cargo, departamento) VALUES ($1,$2,$3,$4,$5) RETURNING id, nome, email', [nome, email, hash, cargo, departamento]);\n    res.json({ sucesso: true, funcionario: result.rows[0] });\n  } catch (e) { res.status(500).json({ erro: e.message }); }\n};",
    "src/controllers/pontoController.js": "const pool = require('../config/database');\nconst cloudinary = require('../config/cloudinary');\nconst multer = require('multer');\nconst upload = multer({ storage: multer.memoryStorage() });\nexports.upload = upload.single('foto');\nexports.registrar = async (req, res) => {\n  try {\n    const { tipo, latitude, longitude, observacao } = req.body;\n    const funcionario_id = req.usuario.id;\n    let foto_url = null;\n    if (req.file) {\n      const result = await new Promise((resolve, reject) => {\n        cloudinary.uploader.upload_stream({ folder: 'pontos' }, (err, r) => { if (err) reject(err); else resolve(r); }).end(req.file.buffer);\n      });\n      foto_url = result.secure_url;\n    }\n    const ponto = await pool.query('INSERT INTO registros_ponto (funcionario_id, tipo, latitude, longitude, foto_url, observacao) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [funcionario_id, tipo, latitude, longitude, foto_url, observacao]);\n    res.json({ sucesso: true, ponto: ponto.rows[0] });\n  } catch (e) { res.status(500).json({ erro: e.message }); }\n};\nexports.meusPontos = async (req, res) => {\n  try {\n    const result = await pool.query('SELECT * FROM registros_ponto WHERE funcionario_id = $1 ORDER BY data_hora DESC LIMIT 50', [req.usuario.id]);\n    res.json(result.rows);\n  } catch (e) { res.status(500).json({ erro: e.message }); }\n};\nexports.todosPontos = async (req, res) => {\n  try {\n    const result = await pool.query('SELECT rp.*, f.nome, f.cargo FROM registros_ponto rp JOIN funcionarios f ON f.id = rp.funcionario_id ORDER BY rp.data_hora DESC', []);\n    res.json(result.rows);\n  } catch (e) { res.status(500).json({ erro: e.message }); }\n};",
    "src/routes/auth.js": "const router = require('express').Router();\nconst { login, cadastrar } = require('../controllers/authController');\nconst auth = require('../middleware/auth');\nrouter.post('/login', login);\nrouter.post('/cadastrar', auth, cadastrar);\nmodule.exports = router;",
    "src/routes/ponto.js": "const router = require('express').Router();\nconst auth = require('../middleware/auth');\nconst { registrar, meusPontos, todosPontos, upload } = require('../controllers/pontoController');\nrouter.post('/registrar', auth, upload, registrar);\nrouter.get('/meus', auth, meusPontos);\nrouter.get('/todos', auth, todosPontos);\nmodule.exports = router;",
    ".env": "PORT=3000\nDATABASE_URL=postgresql://postgres:senha123@localhost:5432/ponto_db\nJWT_SECRET=ponto_secret_key_2024\nCLOUDINARY_CLOUD_NAME=seu_cloud_name\nCLOUDINARY_API_KEY=sua_api_key\nCLOUDINARY_API_SECRET=seu_api_secret\nNODE_ENV=development",
    "database.sql": "CREATE TABLE funcionarios (\n  id SERIAL PRIMARY KEY,\n  nome VARCHAR(100) NOT NULL,\n  email VARCHAR(100) UNIQUE NOT NULL,\n  senha_hash VARCHAR(255) NOT NULL,\n  cargo VARCHAR(100),\n  departamento VARCHAR(100),\n  perfil VARCHAR(20) DEFAULT 'funcionario',\n  ativo BOOLEAN DEFAULT true,\n  criado_em TIMESTAMP DEFAULT NOW()\n);\n\nCREATE TABLE registros_ponto (\n  id SERIAL PRIMARY KEY,\n  funcionario_id INT REFERENCES funcionarios(id),\n  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('entrada','intervalo_inicio','intervalo_fim','saida','hora_extra')),\n  data_hora TIMESTAMP DEFAULT NOW(),\n  latitude DECIMAL(10,8),\n  longitude DECIMAL(11,8),\n  foto_url TEXT,\n  observacao TEXT\n);",
    "server.js": "require('dotenv').config();\nconst express = require('express');\nconst cors = require('cors');\nconst helmet = require('helmet');\nconst app = express();\napp.use(helmet());\napp.use(cors());\napp.use(express.json());\napp.use('/api/auth', require('./src/routes/auth'));\napp.use('/api/ponto', require('./src/routes/ponto'));\napp.get('/api/health', (req, res) => res.json({ status: 'ok', versao: '1.0.0' }));\nconst PORT = process.env.PORT || 3000;\napp.listen(PORT, () => console.log('Servidor rodando na porta ' + PORT));"
}

for filepath, content in files.items():
    os.makedirs(os.path.dirname(filepath) if os.path.dirname(filepath) else ".", exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print("Criado: " + filepath)

print("Backend completo!")
